#!/bin/sh
tput clear
tput civis
echo "     ____  ____  ______       __      __       __   "
echo "    / __ )/ __ \/ ___/ |     / /___ _/ /______/ /_  "
echo "   / __  / / / /\__ \| | /| / / __  / __/ ___/ __ \ "
echo "  / /_/ / /_/ /___/ /| |/ |/ / /_/ / /_/ /__/ / / / "
echo " /_____/\____//____/ |__/|__/\__,_/\__/\___/_/ /_/  "
echo "            German BOS Information Script           "
echo "                 by Bastian Schroll                 "
echo ""
echo "This may take a several minutes... Don't panic!"

MYSQL_ROOT_PASS="root"
RTL_FREQUENZ="123456000"
RTL_DECODE="POC512"
RTL_OFFSET="50"

mkdir -p ~/boswatch/install

tput cup 13 15
echo "[ 1/16] [#---------------]"
tput cup 15 5
echo "-> make a apt-get update................"
apt-get update -y > ~/boswatch/install/setup_log.txt 2>&1

tput cup 13 15
echo "[ 2/16] [##--------------]"
tput cup 15 5
echo "-> download GIT and other stuff.........."
apt-get -y install git cmake build-essential libusb-1.0 qt5-default libpulse-dev libx11-dev sox pwgen >> ~/boswatch/install/setup_log.txt 2>&1
AUTOGENERATED_PASS=`pwgen -c -1 20`

tput cup 13 15
echo "[ 3/16] [###-------------]"
tput cup 15 5
echo "-> download Nginx......................."
apt-get -y install nginx >> ~/boswatch/install/setup_log.txt 2>&1
sed -i "s/worker_processes 4;/worker_processes 1;/g" /etc/nginx/nginx.conf
sed -i "s/worker_connections 768;/worker_connections 128;/g" /etc/nginx/nginx.conf
/etc/init.d/nginx start >> ~/boswatch/install/setup_log.txt 2>&1
                                                                                                                                                 
tput cup 13 15
echo "[ 4/16] [####------------]"
tput cup 15 5
echo "-> download PHP5.............."
apt-get -y install php5 php5-fpm php-pear php5-common php5-mcrypt php5-mysql php5-cli php5-gd php5-mysql >> ~/boswatch/install/setup_log.txt 2>&1

tput cup 13 15
echo "[ 5/16] [#####-----------]"
tput cup 15 5
echo "-> download MYSQL..........."
echo "mysql-server mysql-server/root_password password $MYSQL_ROOT_PASS" | debconf-set-selections
echo "mysql-server mysql-server/root_password_again password $MYSQL_ROOT_PASS" | debconf-set-selections
apt-get -y install mysql-server >> ~/boswatch/install/setup_log.txt 2>&1

tput cup 13 15
echo "[ 6/16] [######----------]"
tput cup 15 5
echo "-> download phpMyAdmin..........."
echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect none" | debconf-set-selections
echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-user string root" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-pass password $MYSQL_ROOT_PASS" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/app-pass password $AUTOGENERATED_PASS" |debconf-set-selections
echo "phpmyadmin phpmyadmin/app-password-confirm password $AUTOGENERATED_PASS" | debconf-set-selections
apt-get -q -y install phpmyadmin >> ~/boswatch/install/setup_log.txt 2>&1
ln -s /usr/share/phpmyadmin /var/www

tput cup 13 15
echo "[ 7/16] [#######---------]"
tput cup 15 5
echo "-> download Caches............"
apt-get -y install php-apc memcached php5-memcache >> ~/boswatch/install/setup_log.txt 2>&1

tput cup 13 15
echo "[ 8/16] [########--------]"
tput cup 15 5
echo "-> Config and Restart Nginx and PHP5.........."
echo '  server {' > /etc/nginx/sites-available/default
echo '    listen 80;' >> /etc/nginx/sites-available/default
echo '    root /var/www;' >> /etc/nginx/sites-available/default
echo '    index index.html index.php;' >> /etc/nginx/sites-available/default
echo '    server_name localhost;' >> /etc/nginx/sites-available/default
echo '    location / {' >> /etc/nginx/sites-available/default
echo '      try_files $uri $uri/ /index.php?$args;' >> /etc/nginx/sites-available/default
echo '      auth_basic "Login";' >> /etc/nginx/sites-available/default
echo '      auth_basic_user_file passwd;' >> /etc/nginx/sites-available/default      
echo '    }' >> /etc/nginx/sites-available/default
echo '    location ~ \.php$ {' >> /etc/nginx/sites-available/default
echo '      try_files $uri =404;' >> /etc/nginx/sites-available/default
echo '      fastcgi_pass unix:/var/run/php5-fpm.sock;' >> /etc/nginx/sites-available/default
echo '      fastcgi_index index.php;' >> /etc/nginx/sites-available/default
echo '      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;' >> /etc/nginx/sites-available/default
echo '      include fastcgi_params;' >> /etc/nginx/sites-available/default
echo '    }' >> /etc/nginx/sites-available/default
echo '  }' >> /etc/nginx/sites-available/default
echo 'dev:$apr1$O9n6L/RL$occnvj/drrTZczuEtWHiB/' > /etc/nginx/passwd
chmod 644 /etc/nginx/passwd
chown www-data:www-data /etc/nginx/passwd
sed -i "s/# gzip_vary on;/gzip_vary on;/g" /etc/nginx/nginx.conf
sed -i "s/# gzip_proxied any;/gzip_proxied any;/g" /etc/nginx/nginx.conf
sed -i "s/# gzip_comp_level 6;/gzip_comp_level 6;/g" /etc/nginx/nginx.conf
sed -i "s/# gzip_buffers 16 8k;/gzip_buffers 16 8k;/g" /etc/nginx/nginx.conf
sed -i "s/# gzip_http_version 1.1;/gzip_http_version 1.1;/g" /etc/nginx/nginx.conf
sed -i "s/# gzip_types text\/plain text\/css application\/json application\/javascript text\/xml application\/xml application\/xml+rss text\/javascript;/gzip_types text\/plain text\/css application\/json application\/javascript text\/xml application\/xml application\/xml+rss text\/javascript;/g" /etc/nginx/nginx.conf
sed -i "s/#include /etc/nginx/conf.d/*.conf;/include /etc/nginx/conf.d/*.conf;/g" /etc/nginx/nginx.conf
sed -i "s/#include /etc/nginx/sites-enabled/*;/include /etc/nginx/sites-enabled/*;/g" /etc/nginx/nginx.conf
php5enmod mcrypt >> ~/boswatch/install/setup_log.txt 2>&1
service nginx restart >> ~/boswatch/install/setup_log.txt 2>&1
service php5-fpm restart >> ~/boswatch/install/setup_log.txt 2>&1

tput cup 13 15
echo "[ 9/16] [#########-------]"
tput cup 15 5
echo "-> download rtl_fm......................"
cd ~/boswatch/install
git clone git://git.osmocom.org/rtl-sdr.git >> ~/boswatch/install/setup_log.txt 2>&1
cd rtl-sdr/

tput cup 13 15
echo "[ 10/16] [##########------]"
tput cup 15 5
echo "-> compile rtl_fm......................"
mkdir -p build && cd build
cmake ../ -DINSTALL_UDEV_RULES=ON >> ~/boswatch/install/setup_log.txt 2>&1
make >> ~/boswatch/install/setup_log.txt 2>&1
make install >> ~/boswatch/install/setup_log.txt 2>&1
ldconfig >> ~/boswatch/install/setup_log.txt 2>&1

tput cup 13 15
echo "[ 11/16] [###########-----]"
tput cup 15 5
echo "-> download multimon-ng................"
cd ~/boswatch/install
git clone https://github.com/EliasOenal/multimonNG.git >> ~/boswatch/install/setup_log.txt 2>&1
cd multimonNG/

tput cup 13 15
echo "[ 12/16] [############----]"
tput cup 15 5
echo "-> compile multimon-ng................."
mkdir -p build
cd build
qmake ../multimon-ng.pro >> ~/boswatch/install/setup_log.txt 2>&1
make >> ~/boswatch/install/setup_log.txt 2>&1
make install >> ~/boswatch/install/setup_log.txt 2>&1

tput cup 13 15
echo "[ 13/16] [#############---]"
tput cup 15 5
echo "-> download MySQL Connector for Python."
cd ~/boswatch/install
wget "http://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python-1.0.9.tar.gz/from/http://cdn.mysql.com/" -O mysql-connector.tar >> ~/boswatch/install/setup_log.txt 2>&1
tar xfv mysql-connector.tar >> ~/boswatch/install/setup_log.txt 2>&1
cd mysql-connector-python*

tput cup 13 15
echo "[ 14/16] [##############--]"
tput cup 15 5
echo "-> install MySQL Connector for Python.."
chmod +x ./setup.py
./setup.py install >> ~/boswatch/install/setup_log.txt 2>&1

tput cup 13 15
echo "[ 15/16] [###############-]"
tput cup 15 5
echo "-> download BOSWatch..................."
cd ~/boswatch
git clone https://github.com/Schrolli91/BOSWatch >> ~/boswatch/install/setup_log.txt 2>&1

tput cup 13 15
echo "[16/16] [################]"
tput cup 15 5
echo "-> configure..........................."
cd ~/boswatch
chmod +x *
echo "# BOSWatch - blacklist the DVB drivers to avoid conflict with the SDR driver\n blacklist dvb_usb_rtl28xxu \n blacklist rtl2830\n blacklist dvb_usb_v2\n blacklist dvb_core" >> /etc/modprobe.d/boswatch_blacklist_sdr.conf

sed -i "s/DIR=/usr/local/bin/BOSWatch;/DIR=/root/boswatch/BOSWatch;/g" ~/boswatch/BOSWatch/service/boswatch.sh
sed -i "s/DAEMON_OPTS="-f xxx -a yyy -s zz -u -q";/DAEMON_OPTS="-f $RTL_FREQUENZ -a $RTL_DECODE -s 0 -e $RTL_OFFSET -u -q";/g" ~/boswatch/BOSWatch/service/boswatch.sh
cp ~/boswatch/BOSWatch/service/boswatch.sh /etc/init.d
update-rc.d boswatch.sh defaults

tput cup 17 1
echo "BOSWatch are now installed in ~/boswatch/"
echo "Install ready!"
